# Generated by Django 3.0.3 on 2020-04-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRegistro',
        ),
    ]
